"""Example DataSphere generator plugin."""


class ExampleGenerator:
    """Example generator — shows how to create a DataSphere plugin."""

    def generate(self, business_request: str, constraints=None) -> dict:
        return {
            "files": {
                "README.md": f"# {business_request}\n\nGenerated by ExampleGenerator plugin.",
                "config.yaml": "# Example configuration\nname: example\n",
            },
            "file_count": 2,
            "generator": "example",
        }
