"""Génère un projet Terraform complet à partir des contraintes d'architecture."""
from __future__ import annotations
from dataclasses import dataclass, field
from pathlib import Path
from datasphere.models.request import ArchitectureConstraints


@dataclass
class TerraformProjectFiles:
    files: dict[str, str] = field(default_factory=dict)

    def write(self, output_dir: str) -> list[str]:
        base = Path(output_dir) / "terraform"
        written = []
        for rel_path, content in self.files.items():
            p = base / rel_path
            p.parent.mkdir(parents=True, exist_ok=True)
            p.write_text(content, encoding="utf-8")
            written.append(str(p))
        return written


class TerraformGenerator:
    """Génère un projet Terraform 1.5+ pour la plateforme DataSphere."""

    # Budget → instance sizing maps
    _AWS_DB_INSTANCE = {"low": "db.t3.small", "medium": "db.r5.large", "enterprise": "db.r5.4xlarge"}
    _AWS_REDSHIFT_NODE = {"low": "dc2.large", "medium": "ra3.xlplus", "enterprise": "ra3.4xlarge"}
    _GCP_MACHINE = {"low": "n1-standard-2", "medium": "n1-standard-4", "enterprise": "n1-standard-16"}
    _AZURE_VM = {"low": "Standard_B2s", "medium": "Standard_D4s_v3", "enterprise": "Standard_E16s_v3"}

    def generate(
        self,
        business_request: str,
        constraints: ArchitectureConstraints,
    ) -> TerraformProjectFiles:
        c = constraints
        provider = c.cloud_provider.lower()
        warehouse = c.data_warehouse.lower()
        deployment = c.deployment.lower()
        budget = c.budget or "medium"
        region = c.region or self._default_region(provider)
        use_k8s = deployment in ("kubernetes", "helm", "k8s")
        has_lake = bool(c.data_lake) and c.data_lake.lower() not in ("none", "")

        files: dict[str, str] = {}

        files["main.tf"] = self._main_tf(c, provider, region, use_k8s, has_lake)
        files["variables.tf"] = self._variables_tf(c, provider, region)
        files["outputs.tf"] = self._outputs_tf(provider, warehouse, use_k8s, has_lake)
        files["terraform.tfvars.example"] = self._tfvars_example(c, provider, region)
        files["backend.tf"] = self._backend_tf(provider)
        files[".gitignore"] = self._gitignore()
        files["README.md"] = self._readme(business_request, c)

        files["modules/networking/main.tf"] = self._networking_module(provider)
        files["modules/warehouse/main.tf"] = self._warehouse_module(provider, warehouse, budget)
        files["modules/iam/main.tf"] = self._iam_module(provider)

        if has_lake:
            files["modules/storage/main.tf"] = self._storage_module(provider, c.data_lake.lower())

        if use_k8s:
            files["modules/kubernetes/main.tf"] = self._kubernetes_module(provider, budget)
            files["modules/monitoring/main.tf"] = self._monitoring_module()

        return TerraformProjectFiles(files=files)

    # ------------------------------------------------------------------ #
    #  Top-level files                                                     #
    # ------------------------------------------------------------------ #

    def _default_region(self, provider: str) -> str:
        return {"aws": "eu-west-1", "gcp": "europe-west1", "azure": "westeurope"}.get(provider, "eu-west-1")

    def _main_tf(self, c: ArchitectureConstraints, provider: str, region: str, use_k8s: bool, has_lake: bool) -> str:
        warehouse = c.data_warehouse.lower()
        budget = c.budget or "medium"
        snowflake_provider = ""
        databricks_provider = ""
        helm_provider = ""
        k8s_provider = ""

        extra_providers = ""
        if warehouse == "snowflake":
            snowflake_provider = """
    snowflake = {
      source  = "Snowflake-Labs/snowflake"
      version = "~> 0.87"
    }"""
        if warehouse == "databricks":
            databricks_provider = """
    databricks = {
      source  = "databricks/databricks"
      version = "~> 1.36"
    }"""
        if use_k8s:
            helm_provider = """
    helm = {
      source  = "hashicorp/helm"
      version = "~> 2.12"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "~> 2.25"
    }"""

        required_providers = self._required_providers_block(provider, snowflake_provider, databricks_provider, helm_provider)

        provider_config = self._provider_config_block(provider, region, warehouse)

        module_calls = self._module_calls(provider, warehouse, use_k8s, has_lake, budget)

        return f"""# ============================================================
# main.tf — DataSphere platform infrastructure
# Generated by DataSphere TerraformGenerator
# Cloud: {provider}  |  Warehouse: {warehouse}
# ============================================================

terraform {{
  required_version = ">= 1.5.0"

  required_providers {{
{required_providers}  }}
}}

{provider_config}

{module_calls}
"""

    def _required_providers_block(self, provider: str, snowflake: str, databricks: str, helm: str) -> str:
        if provider == "aws":
            base = """    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }"""
        elif provider == "gcp":
            base = """    google = {
      source  = "hashicorp/google"
      version = "~> 5.0"
    }"""
        elif provider == "azure":
            base = """    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.90"
    }"""
        else:
            base = """    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "~> 2.25"
    }"""
        return base + snowflake + databricks + helm + "\n"

    def _provider_config_block(self, provider: str, region: str, warehouse: str) -> str:
        if provider == "aws":
            block = f"""provider "aws" {{
  region = var.region

  default_tags {{
    tags = {{
      Project     = var.project_name
      Environment = var.environment
      ManagedBy   = "terraform"
    }}
  }}
}}"""
        elif provider == "gcp":
            block = f"""provider "google" {{
  project = var.gcp_project
  region  = var.region
}}"""
        elif provider == "azure":
            block = """provider "azurerm" {
  features {}

  subscription_id = var.azure_subscription_id
  tenant_id       = var.azure_tenant_id
}"""
        else:
            block = """provider "kubernetes" {
  config_path    = var.kubeconfig_path
  config_context = var.kube_context
}"""

        snowflake_provider = ""
        if warehouse == "snowflake":
            snowflake_provider = """
provider "snowflake" {
  account  = var.snowflake_account
  username = var.snowflake_username
  password = var.snowflake_password
  role     = var.snowflake_role
}"""

        databricks_provider = ""
        if warehouse == "databricks":
            if provider == "aws":
                databricks_provider = """
provider "databricks" {
  host  = module.warehouse.workspace_url
  token = var.databricks_token
}"""
            else:
                databricks_provider = """
provider "databricks" {
  azure_workspace_resource_id = module.warehouse.workspace_id
  azure_client_id             = var.azure_client_id
  azure_client_secret         = var.azure_client_secret
  azure_tenant_id             = var.azure_tenant_id
}"""

        return block + snowflake_provider + databricks_provider

    def _module_calls(self, provider: str, warehouse: str, use_k8s: bool, has_lake: bool, budget: str) -> str:
        blocks = []

        if provider in ("aws", "gcp", "azure"):
            blocks.append("""module "networking" {
  source = "./modules/networking"

  project_name = var.project_name
  environment  = var.environment
  region       = var.region
}""")

        blocks.append(f"""module "iam" {{
  source = "./modules/iam"

  project_name = var.project_name
  environment  = var.environment
  {self._iam_module_extra_args(provider)}
}}""")

        wh_args = self._warehouse_module_args(provider, warehouse, budget)
        blocks.append(f"""module "warehouse" {{
  source = "./modules/warehouse"

  project_name = var.project_name
  environment  = var.environment
{wh_args}
}}""")

        if has_lake:
            blocks.append(f"""module "storage" {{
  source = "./modules/storage"

  project_name = var.project_name
  environment  = var.environment
  region       = var.region
  {self._storage_module_args(provider)}
}}""")

        if use_k8s:
            blocks.append(f"""module "kubernetes" {{
  source = "./modules/kubernetes"

  project_name   = var.project_name
  environment    = var.environment
  region         = var.region
  {self._k8s_module_args(provider, budget)}
}}

module "monitoring" {{
  source = "./modules/monitoring"

  depends_on = [module.kubernetes]

  project_name = var.project_name
  environment  = var.environment
}}""")

        return "\n\n".join(blocks)

    def _iam_module_extra_args(self, provider: str) -> str:
        if provider == "aws":
            return "bucket_name    = try(module.storage.bucket_name, \"\")"
        elif provider == "gcp":
            return "gcp_project    = var.gcp_project"
        elif provider == "azure":
            return "resource_group = module.networking.resource_group_name"
        return ""

    def _warehouse_module_args(self, provider: str, warehouse: str, budget: str) -> str:
        lines = []
        if warehouse == "snowflake":
            lines += [
                "  snowflake_account  = var.snowflake_account",
                "  snowflake_username = var.snowflake_username",
                "  snowflake_password = var.snowflake_password",
                "  snowflake_role     = var.snowflake_role",
            ]
        elif warehouse == "bigquery":
            lines += ["  gcp_project = var.gcp_project", "  region      = var.region"]
        elif warehouse == "redshift":
            lines += [
                "  vpc_id            = module.networking.vpc_id",
                "  subnet_ids        = module.networking.private_subnet_ids",
                "  db_password       = var.warehouse_password",
                f"  node_type         = \"{self._AWS_REDSHIFT_NODE.get(budget, 'ra3.xlplus')}\"",
            ]
        elif warehouse in ("postgresql", "postgres"):
            if provider == "aws":
                lines += [
                    "  vpc_id            = module.networking.vpc_id",
                    "  subnet_ids        = module.networking.private_subnet_ids",
                    "  db_password       = var.warehouse_password",
                    f"  instance_class    = \"{self._AWS_DB_INSTANCE.get(budget, 'db.r5.large')}\"",
                ]
            elif provider == "gcp":
                lines += [
                    "  gcp_project   = var.gcp_project",
                    "  region        = var.region",
                    "  db_password   = var.warehouse_password",
                    f"  machine_type  = \"{self._GCP_MACHINE.get(budget, 'n1-standard-4')}\"",
                ]
        elif warehouse == "databricks":
            if provider == "aws":
                lines += [
                    "  vpc_id     = module.networking.vpc_id",
                    "  subnet_ids = module.networking.private_subnet_ids",
                ]
            elif provider == "azure":
                lines += [
                    "  resource_group = module.networking.resource_group_name",
                    "  location       = var.region",
                ]
        elif warehouse in ("azure-synapse", "synapse"):
            lines += [
                "  resource_group   = module.networking.resource_group_name",
                "  location         = var.region",
                "  synapse_password = var.warehouse_password",
            ]
        elif warehouse == "clickhouse":
            lines += ["  namespace = var.environment"]

        return "\n".join(lines)

    def _storage_module_args(self, provider: str) -> str:
        if provider == "gcp":
            return "gcp_project = var.gcp_project"
        elif provider == "azure":
            return "resource_group = module.networking.resource_group_name"
        return ""

    def _k8s_module_args(self, provider: str, budget: str) -> str:
        if provider == "aws":
            instance = {"low": "t3.medium", "medium": "m5.xlarge", "enterprise": "m5.4xlarge"}.get(budget, "m5.xlarge")
            return f"""vpc_id         = module.networking.vpc_id
  subnet_ids     = module.networking.private_subnet_ids
  instance_type  = "{instance}\""""
        elif provider == "gcp":
            machine = self._GCP_MACHINE.get(budget, "n1-standard-4")
            return f"""network    = module.networking.network_name
  subnetwork = module.networking.subnetwork_name
  machine_type = "{machine}\""""
        elif provider == "azure":
            vm = self._AZURE_VM.get(budget, "Standard_D4s_v3")
            return f"""resource_group = module.networking.resource_group_name
  location       = var.region
  vm_size        = "{vm}\""""
        return ""

    def _variables_tf(self, c: ArchitectureConstraints, provider: str, region: str) -> str:
        provider = c.cloud_provider.lower()
        warehouse = c.data_warehouse.lower()
        budget = c.budget or "medium"

        vars_hcl = f"""# ============================================================
# variables.tf — Input variables for the DataSphere platform
# ============================================================

variable "project_name" {{
  description = "Name of the DataSphere project (used as prefix for all resources)"
  type        = string
  default     = "datasphere"
}}

variable "environment" {{
  description = "Deployment environment (dev / staging / prod)"
  type        = string
  default     = "prod"

  validation {{
    condition     = contains(["dev", "staging", "prod"], var.environment)
    error_message = "environment must be one of: dev, staging, prod."
  }}
}}

variable "region" {{
  description = "Cloud region for resource deployment"
  type        = string
  default     = "{region}"
}}

"""

        if provider == "aws":
            vars_hcl += """variable "aws_account_id" {
  description = "AWS account ID"
  type        = string
}

"""
        elif provider == "gcp":
            vars_hcl += """variable "gcp_project" {
  description = "GCP project ID"
  type        = string
}

"""
        elif provider == "azure":
            vars_hcl += """variable "azure_subscription_id" {
  description = "Azure subscription ID"
  type        = string
}

variable "azure_tenant_id" {
  description = "Azure Active Directory tenant ID"
  type        = string
}

variable "azure_client_id" {
  description = "Azure service principal client ID"
  type        = string
  sensitive   = true
}

variable "azure_client_secret" {
  description = "Azure service principal client secret"
  type        = string
  sensitive   = true
}

"""
        else:
            vars_hcl += """variable "kubeconfig_path" {
  description = "Path to the kubeconfig file"
  type        = string
  default     = "~/.kube/config"
}

variable "kube_context" {
  description = "Kubernetes context to use"
  type        = string
  default     = "default"
}

"""

        if warehouse == "snowflake":
            vars_hcl += """variable "snowflake_account" {
  description = "Snowflake account identifier (e.g. xy12345.eu-west-1)"
  type        = string
}

variable "snowflake_username" {
  description = "Snowflake admin username"
  type        = string
}

variable "snowflake_password" {
  description = "Snowflake admin password"
  type        = string
  sensitive   = true
}

variable "snowflake_role" {
  description = "Snowflake role to use (e.g. SYSADMIN)"
  type        = string
  default     = "SYSADMIN"
}

"""

        if warehouse in ("redshift", "postgresql", "postgres", "azure-synapse", "synapse"):
            vars_hcl += """variable "warehouse_password" {
  description = "Password for the data warehouse database user"
  type        = string
  sensitive   = true
}

"""

        if warehouse == "databricks":
            vars_hcl += """variable "databricks_token" {
  description = "Databricks personal access token"
  type        = string
  sensitive   = true
}

"""

        vars_hcl += f"""variable "tags" {{
  description = "Additional tags to apply to all resources"
  type        = map(string)
  default     = {{}}
}}
"""
        return vars_hcl

    def _outputs_tf(self, provider: str, warehouse: str, use_k8s: bool, has_lake: bool) -> str:
        out = """# ============================================================
# outputs.tf — Platform outputs (endpoints, ARNs, connection strings)
# ============================================================

"""
        if provider == "aws":
            out += """output "vpc_id" {
  description = "VPC ID"
  value       = module.networking.vpc_id
}

output "private_subnet_ids" {
  description = "Private subnet IDs"
  value       = module.networking.private_subnet_ids
}

"""
        elif provider == "gcp":
            out += """output "network_name" {
  description = "VPC network name"
  value       = module.networking.network_name
}

"""
        elif provider == "azure":
            out += """output "resource_group_name" {
  description = "Azure resource group name"
  value       = module.networking.resource_group_name
}

output "vnet_id" {
  description = "Virtual Network ID"
  value       = module.networking.vnet_id
}

"""

        if warehouse == "snowflake":
            out += """output "snowflake_database" {
  description = "Snowflake database name"
  value       = module.warehouse.database_name
}

output "snowflake_warehouse" {
  description = "Snowflake virtual warehouse name"
  value       = module.warehouse.warehouse_name
}

"""
        elif warehouse == "bigquery":
            out += """output "bigquery_dataset_id" {
  description = "BigQuery dataset ID"
  value       = module.warehouse.dataset_id
}

"""
        elif warehouse == "redshift":
            out += """output "redshift_endpoint" {
  description = "Redshift cluster endpoint"
  value       = module.warehouse.cluster_endpoint
}

output "redshift_port" {
  description = "Redshift cluster port"
  value       = module.warehouse.cluster_port
}

"""
        elif warehouse in ("postgresql", "postgres"):
            out += """output "warehouse_endpoint" {
  description = "Database endpoint hostname"
  value       = module.warehouse.endpoint
}

output "warehouse_port" {
  description = "Database port"
  value       = module.warehouse.port
}

"""
        elif warehouse in ("azure-synapse", "synapse"):
            out += """output "synapse_workspace_name" {
  description = "Azure Synapse workspace name"
  value       = module.warehouse.workspace_name
}

output "synapse_sql_endpoint" {
  description = "Azure Synapse dedicated SQL endpoint"
  value       = module.warehouse.sql_endpoint
}

"""
        elif warehouse == "databricks":
            out += """output "databricks_workspace_url" {
  description = "Databricks workspace URL"
  value       = module.warehouse.workspace_url
}

"""

        if has_lake:
            out += """output "data_lake_bucket" {
  description = "Data lake storage bucket/container name"
  value       = module.storage.bucket_name
}

output "data_lake_uri" {
  description = "Data lake URI (s3://, gs://, abfss://)"
  value       = module.storage.bucket_uri
}

"""

        if use_k8s:
            out += """output "kubernetes_cluster_name" {
  description = "Kubernetes cluster name"
  value       = module.kubernetes.cluster_name
}

output "kubernetes_endpoint" {
  description = "Kubernetes API server endpoint"
  value       = module.kubernetes.cluster_endpoint
  sensitive   = true
}

output "grafana_url" {
  description = "Grafana dashboard URL (via LoadBalancer or port-forward)"
  value       = module.monitoring.grafana_url
}

"""
        return out

    def _tfvars_example(self, c: ArchitectureConstraints, provider: str, region: str) -> str:
        warehouse = c.data_warehouse.lower()
        budget = c.budget or "medium"

        lines = [
            "# terraform.tfvars.example",
            "# Copy to terraform.tfvars and fill in your values.",
            "# NEVER commit terraform.tfvars to version control.",
            "",
            f'project_name = "datasphere"',
            f'environment  = "prod"',
            f'region       = "{region}"',
            "",
        ]

        if provider == "aws":
            lines += ['aws_account_id = "123456789012"', ""]
        elif provider == "gcp":
            lines += ['gcp_project = "my-gcp-project-id"', ""]
        elif provider == "azure":
            lines += [
                'azure_subscription_id = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"',
                'azure_tenant_id       = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"',
                'azure_client_id       = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"',
                'azure_client_secret   = "your-client-secret"',
                "",
            ]
        else:
            lines += ['kubeconfig_path = "~/.kube/config"', 'kube_context    = "default"', ""]

        if warehouse == "snowflake":
            lines += [
                'snowflake_account  = "xy12345.eu-west-1"',
                'snowflake_username = "terraform_admin"',
                'snowflake_password = "change-me-strong-password"',
                'snowflake_role     = "SYSADMIN"',
                "",
            ]

        if warehouse in ("redshift", "postgresql", "postgres", "azure-synapse", "synapse"):
            lines += ['warehouse_password = "change-me-strong-password"', ""]

        if warehouse == "databricks":
            lines += ['databricks_token = "dapi-your-token-here"', ""]

        lines += [
            'tags = {',
            '  Owner   = "data-platform-team"',
            '  CostCenter = "data-engineering"',
            '}',
        ]

        return "\n".join(lines) + "\n"

    def _backend_tf(self, provider: str) -> str:
        if provider == "aws":
            return """# backend.tf — Remote state in S3 + DynamoDB lock
terraform {
  backend "s3" {
    bucket         = "datasphere-terraform-state"
    key            = "datasphere/terraform.tfstate"
    region         = "eu-west-1"
    encrypt        = true
    dynamodb_table = "datasphere-terraform-lock"
  }
}
"""
        elif provider == "gcp":
            return """# backend.tf — Remote state in GCS
terraform {
  backend "gcs" {
    bucket = "datasphere-terraform-state"
    prefix = "datasphere/state"
  }
}
"""
        elif provider == "azure":
            return """# backend.tf — Remote state in Azure Blob Storage
terraform {
  backend "azurerm" {
    resource_group_name  = "datasphere-tfstate-rg"
    storage_account_name = "dataspheretfstate"
    container_name       = "tfstate"
    key                  = "datasphere.terraform.tfstate"
  }
}
"""
        else:
            return """# backend.tf — Local backend (development only)
# For production, migrate to a remote backend (S3, GCS, Azure Blob).
terraform {
  backend "local" {
    path = "terraform.tfstate"
  }
}
"""

    def _gitignore(self) -> str:
        return """# Terraform state files
*.tfstate
*.tfstate.*
*.tfstate.backup

# Terraform plan output
*.tfplan

# Terraform working directory
.terraform/
.terraform.lock.hcl

# Variable files with secrets
terraform.tfvars
*.auto.tfvars

# Crash log files
crash.log
crash.*.log

# Override files
override.tf
override.tf.json
*_override.tf
*_override.tf.json

# Terraform CLI configuration
.terraformrc
terraform.rc
"""

    def _readme(self, business_request: str, c: ArchitectureConstraints) -> str:
        provider = c.cloud_provider.lower()
        warehouse = c.data_warehouse.lower()
        deployment = c.deployment.lower()
        use_k8s = deployment in ("kubernetes", "helm", "k8s")

        backend_prereqs = ""
        if provider == "aws":
            backend_prereqs = """\
### Pre-requisites (AWS backend)

```bash
# Create the S3 bucket and DynamoDB table for state storage
aws s3api create-bucket --bucket datasphere-terraform-state --region eu-west-1 \\
  --create-bucket-configuration LocationConstraint=eu-west-1
aws s3api put-bucket-versioning --bucket datasphere-terraform-state \\
  --versioning-configuration Status=Enabled
aws dynamodb create-table --table-name datasphere-terraform-lock \\
  --attribute-definitions AttributeName=LockID,AttributeType=S \\
  --key-schema AttributeName=LockID,KeyType=HASH \\
  --billing-mode PAY_PER_REQUEST --region eu-west-1
```
"""
        elif provider == "gcp":
            backend_prereqs = """\
### Pre-requisites (GCS backend)

```bash
gsutil mb -l europe-west1 gs://datasphere-terraform-state
gsutil versioning set on gs://datasphere-terraform-state
```
"""
        elif provider == "azure":
            backend_prereqs = """\
### Pre-requisites (Azure backend)

```bash
az group create --name datasphere-tfstate-rg --location westeurope
az storage account create --name dataspheretfstate \\
  --resource-group datasphere-tfstate-rg --sku Standard_LRS
az storage container create --name tfstate \\
  --account-name dataspheredfstate
```
"""

        modules_table_rows = [
            "| networking | VPC / Subnets / Security Groups |",
            "| iam        | IAM roles and policies          |",
            f"| warehouse  | {warehouse.capitalize()} data warehouse    |",
        ]
        if bool(c.data_lake) and c.data_lake.lower() not in ("none", ""):
            modules_table_rows.append("| storage    | Data lake bucket / container    |")
        if use_k8s:
            modules_table_rows.append("| kubernetes | EKS / GKE / AKS cluster         |")
            modules_table_rows.append("| monitoring | Prometheus + Grafana (Helm)      |")

        modules_table = "\n".join(modules_table_rows)

        return f"""# Terraform — DataSphere Platform

> {business_request}

## Stack

| Layer       | Choice               |
|-------------|----------------------|
| Cloud       | {c.cloud_provider}   |
| Warehouse   | {c.data_warehouse}   |
| Deployment  | {c.deployment}       |
| Budget      | {c.budget}           |
| Region      | {c.region or 'default'} |

## Quick Start

```bash
# 1. Copy and fill variables
cp terraform.tfvars.example terraform.tfvars
$EDITOR terraform.tfvars

# 2. Initialise Terraform
terraform init

# 3. Review the plan
terraform plan -out=tfplan

# 4. Apply
terraform apply tfplan
```

## Module Structure

| Module     | Description                     |
|------------|---------------------------------|
{modules_table}

## Key Variables

| Variable | Description |
|----------|-------------|
| `project_name` | Prefix for all resource names |
| `environment`  | dev / staging / prod |
| `region`       | Cloud region ({c.region or 'uses provider default'}) |

{backend_prereqs}
## Destroying

```bash
terraform destroy
```

> **Warning:** Destroying the warehouse module will delete all data.
> Ensure you have backups before running `terraform destroy`.

## Outputs

After `terraform apply`, the following outputs are available:

```bash
terraform output          # list all
terraform output -json    # JSON format
```
"""

    # ------------------------------------------------------------------ #
    #  Module files                                                        #
    # ------------------------------------------------------------------ #

    def _networking_module(self, provider: str) -> str:
        if provider == "aws":
            return """# modules/networking/main.tf — AWS VPC + Subnets + Security Groups

variable "project_name" { type = string }
variable "environment"  { type = string }
variable "region"       { type = string }

locals {
  name_prefix = "${var.project_name}-${var.environment}"
  tags = {
    Project     = var.project_name
    Environment = var.environment
    ManagedBy   = "terraform"
  }
}

data "aws_availability_zones" "available" {
  state = "available"
}

resource "aws_vpc" "main" {
  cidr_block           = "10.0.0.0/16"
  enable_dns_hostnames = true
  enable_dns_support   = true

  tags = merge(local.tags, { Name = "${local.name_prefix}-vpc" })
}

resource "aws_internet_gateway" "main" {
  vpc_id = aws_vpc.main.id
  tags   = merge(local.tags, { Name = "${local.name_prefix}-igw" })
}

resource "aws_subnet" "private" {
  count             = 2
  vpc_id            = aws_vpc.main.id
  cidr_block        = cidrsubnet("10.0.0.0/16", 8, count.index)
  availability_zone = data.aws_availability_zones.available.names[count.index]

  tags = merge(local.tags, {
    Name = "${local.name_prefix}-private-${count.index + 1}"
    Tier = "private"
  })
}

resource "aws_subnet" "public" {
  count                   = 2
  vpc_id                  = aws_vpc.main.id
  cidr_block              = cidrsubnet("10.0.0.0/16", 8, count.index + 10)
  availability_zone       = data.aws_availability_zones.available.names[count.index]
  map_public_ip_on_launch = true

  tags = merge(local.tags, {
    Name = "${local.name_prefix}-public-${count.index + 1}"
    Tier = "public"
  })
}

resource "aws_eip" "nat" {
  count  = 1
  domain = "vpc"
  tags   = merge(local.tags, { Name = "${local.name_prefix}-nat-eip" })
}

resource "aws_nat_gateway" "main" {
  allocation_id = aws_eip.nat[0].id
  subnet_id     = aws_subnet.public[0].id
  tags          = merge(local.tags, { Name = "${local.name_prefix}-nat" })
  depends_on    = [aws_internet_gateway.main]
}

resource "aws_route_table" "private" {
  vpc_id = aws_vpc.main.id
  route {
    cidr_block     = "0.0.0.0/0"
    nat_gateway_id = aws_nat_gateway.main.id
  }
  tags = merge(local.tags, { Name = "${local.name_prefix}-private-rt" })
}

resource "aws_route_table_association" "private" {
  count          = length(aws_subnet.private)
  subnet_id      = aws_subnet.private[count.index].id
  route_table_id = aws_route_table.private.id
}

resource "aws_security_group" "platform" {
  name        = "${local.name_prefix}-platform-sg"
  description = "DataSphere platform security group"
  vpc_id      = aws_vpc.main.id

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
    description = "Allow all outbound"
  }

  tags = merge(local.tags, { Name = "${local.name_prefix}-platform-sg" })
}

output "vpc_id"              { value = aws_vpc.main.id }
output "private_subnet_ids"  { value = aws_subnet.private[*].id }
output "public_subnet_ids"   { value = aws_subnet.public[*].id }
output "platform_sg_id"      { value = aws_security_group.platform.id }
"""
        elif provider == "gcp":
            return """# modules/networking/main.tf — GCP VPC + Subnets

variable "project_name" { type = string }
variable "environment"  { type = string }
variable "region"       { type = string }

locals {
  name_prefix = "${var.project_name}-${var.environment}"
  labels = {
    project     = var.project_name
    environment = var.environment
    managed_by  = "terraform"
  }
}

resource "google_compute_network" "main" {
  name                    = "${local.name_prefix}-vpc"
  auto_create_subnetworks = false
}

resource "google_compute_subnetwork" "private" {
  name          = "${local.name_prefix}-private-subnet"
  ip_cidr_range = "10.0.1.0/24"
  region        = var.region
  network       = google_compute_network.main.id

  private_ip_google_access = true

  secondary_ip_range {
    range_name    = "pods"
    ip_cidr_range = "10.1.0.0/16"
  }

  secondary_ip_range {
    range_name    = "services"
    ip_cidr_range = "10.2.0.0/20"
  }
}

resource "google_compute_router" "main" {
  name    = "${local.name_prefix}-router"
  region  = var.region
  network = google_compute_network.main.id
}

resource "google_compute_router_nat" "main" {
  name                               = "${local.name_prefix}-nat"
  router                             = google_compute_router.main.name
  region                             = var.region
  nat_ip_allocate_option             = "AUTO_ONLY"
  source_subnetwork_ip_ranges_to_nat = "ALL_SUBNETWORKS_ALL_IP_RANGES"
}

resource "google_compute_firewall" "allow_internal" {
  name    = "${local.name_prefix}-allow-internal"
  network = google_compute_network.main.name

  allow {
    protocol = "tcp"
    ports    = ["0-65535"]
  }

  source_ranges = ["10.0.0.0/8"]
}

output "network_name"    { value = google_compute_network.main.name }
output "network_id"      { value = google_compute_network.main.id }
output "subnetwork_name" { value = google_compute_subnetwork.private.name }
output "subnetwork_id"   { value = google_compute_subnetwork.private.id }
"""
        elif provider == "azure":
            return """# modules/networking/main.tf — Azure VNet + Subnets + NSG

variable "project_name" { type = string }
variable "environment"  { type = string }
variable "region"       { type = string }

locals {
  name_prefix = "${var.project_name}-${var.environment}"
  tags = {
    Project     = var.project_name
    Environment = var.environment
    ManagedBy   = "terraform"
  }
}

resource "azurerm_resource_group" "main" {
  name     = "${local.name_prefix}-rg"
  location = var.region
  tags     = local.tags
}

resource "azurerm_virtual_network" "main" {
  name                = "${local.name_prefix}-vnet"
  resource_group_name = azurerm_resource_group.main.name
  location            = azurerm_resource_group.main.location
  address_space       = ["10.0.0.0/16"]
  tags                = local.tags
}

resource "azurerm_subnet" "private" {
  name                 = "${local.name_prefix}-private-subnet"
  resource_group_name  = azurerm_resource_group.main.name
  virtual_network_name = azurerm_virtual_network.main.name
  address_prefixes     = ["10.0.1.0/24"]
}

resource "azurerm_subnet" "public" {
  name                 = "${local.name_prefix}-public-subnet"
  resource_group_name  = azurerm_resource_group.main.name
  virtual_network_name = azurerm_virtual_network.main.name
  address_prefixes     = ["10.0.2.0/24"]
}

resource "azurerm_network_security_group" "platform" {
  name                = "${local.name_prefix}-nsg"
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name

  security_rule {
    name                       = "AllowInternalInbound"
    priority                   = 100
    direction                  = "Inbound"
    access                     = "Allow"
    protocol                   = "*"
    source_port_range          = "*"
    destination_port_range     = "*"
    source_address_prefix      = "VirtualNetwork"
    destination_address_prefix = "VirtualNetwork"
  }

  tags = local.tags
}

resource "azurerm_subnet_network_security_group_association" "private" {
  subnet_id                 = azurerm_subnet.private.id
  network_security_group_id = azurerm_network_security_group.platform.id
}

output "resource_group_name"  { value = azurerm_resource_group.main.name }
output "vnet_id"              { value = azurerm_virtual_network.main.id }
output "private_subnet_id"    { value = azurerm_subnet.private.id }
output "public_subnet_id"     { value = azurerm_subnet.public.id }
"""
        else:
            return """# modules/networking/main.tf — Minimal (local/kubernetes provider)

variable "project_name" { type = string }
variable "environment"  { type = string }
variable "region"       { type = string }

# No cloud networking required for local-docker / kubernetes deployments.
# Networking is handled by the k8s CNI plugin (e.g. Calico, Cilium).

resource "kubernetes_namespace" "platform" {
  metadata {
    name = "${var.project_name}-${var.environment}"
    labels = {
      "app.kubernetes.io/managed-by" = "terraform"
      environment                    = var.environment
    }
  }
}

output "namespace" { value = kubernetes_namespace.platform.metadata[0].name }
"""

    def _warehouse_module(self, provider: str, warehouse: str, budget: str) -> str:
        if warehouse == "snowflake":
            return """# modules/warehouse/main.tf — Snowflake database + warehouse + schema

variable "project_name"       { type = string }
variable "environment"        { type = string }
variable "snowflake_account"  { type = string }
variable "snowflake_username" { type = string }
variable "snowflake_password" { type = string; sensitive = true }
variable "snowflake_role"     { type = string; default = "SYSADMIN" }

locals {
  db_name = upper("${var.project_name}_${var.environment}")
  wh_name = upper("${var.project_name}_WH_${var.environment}")
}

resource "snowflake_database" "main" {
  name    = local.db_name
  comment = "DataSphere platform database — ${var.environment}"
}

resource "snowflake_warehouse" "main" {
  name           = local.wh_name
  warehouse_size = "SMALL"
  auto_suspend   = 60
  auto_resume    = true
  comment        = "DataSphere virtual warehouse"
}

resource "snowflake_schema" "raw" {
  database = snowflake_database.main.name
  name     = "RAW"
  comment  = "Raw ingestion layer"
}

resource "snowflake_schema" "staging" {
  database = snowflake_database.main.name
  name     = "STAGING"
  comment  = "Staging / cleansing layer"
}

resource "snowflake_schema" "marts" {
  database = snowflake_database.main.name
  name     = "MARTS"
  comment  = "Data mart / serving layer"
}

output "database_name"  { value = snowflake_database.main.name }
output "warehouse_name" { value = snowflake_warehouse.main.name }
output "raw_schema"     { value = snowflake_schema.raw.name }
output "staging_schema" { value = snowflake_schema.staging.name }
output "marts_schema"   { value = snowflake_schema.marts.name }
"""

        elif warehouse == "bigquery":
            return """# modules/warehouse/main.tf — BigQuery datasets

variable "project_name" { type = string }
variable "environment"  { type = string }
variable "gcp_project"  { type = string }
variable "region"       { type = string }

locals {
  labels = {
    project     = var.project_name
    environment = var.environment
    managed_by  = "terraform"
  }
}

resource "google_bigquery_dataset" "raw" {
  dataset_id  = "${var.project_name}_${var.environment}_raw"
  project     = var.gcp_project
  location    = var.region
  description = "Raw ingestion layer"
  labels      = local.labels

  delete_contents_on_destroy = false
}

resource "google_bigquery_dataset" "staging" {
  dataset_id  = "${var.project_name}_${var.environment}_staging"
  project     = var.gcp_project
  location    = var.region
  description = "Staging / transformation layer"
  labels      = local.labels
}

resource "google_bigquery_dataset" "marts" {
  dataset_id  = "${var.project_name}_${var.environment}_marts"
  project     = var.gcp_project
  location    = var.region
  description = "Data mart / serving layer"
  labels      = local.labels
}

output "dataset_id"         { value = google_bigquery_dataset.raw.dataset_id }
output "raw_dataset_id"     { value = google_bigquery_dataset.raw.dataset_id }
output "staging_dataset_id" { value = google_bigquery_dataset.staging.dataset_id }
output "marts_dataset_id"   { value = google_bigquery_dataset.marts.dataset_id }
"""

        elif warehouse == "redshift":
            node_type = self._AWS_REDSHIFT_NODE.get(budget, "ra3.xlplus")
            num_nodes = {"low": 1, "medium": 2, "enterprise": 4}.get(budget, 2)
            return f"""# modules/warehouse/main.tf — Amazon Redshift cluster

variable "project_name" {{ type = string }}
variable "environment"  {{ type = string }}
variable "vpc_id"       {{ type = string }}
variable "subnet_ids"   {{ type = list(string) }}
variable "db_password"  {{ type = string; sensitive = true }}
variable "node_type"    {{ type = string; default = "{node_type}" }}

locals {{
  name_prefix = "${{var.project_name}}-${{var.environment}}"
  tags = {{
    Project     = var.project_name
    Environment = var.environment
    ManagedBy   = "terraform"
  }}
}}

resource "aws_redshift_subnet_group" "main" {{
  name       = "${{local.name_prefix}}-redshift-sg"
  subnet_ids = var.subnet_ids
  tags       = local.tags
}}

resource "aws_security_group" "redshift" {{
  name        = "${{local.name_prefix}}-redshift"
  description = "Redshift cluster security group"
  vpc_id      = var.vpc_id

  ingress {{
    from_port   = 5439
    to_port     = 5439
    protocol    = "tcp"
    cidr_blocks = ["10.0.0.0/8"]
    description = "Redshift port from internal network"
  }}

  egress {{
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }}

  tags = local.tags
}}

resource "aws_redshift_cluster" "main" {{
  cluster_identifier        = "${{local.name_prefix}}-redshift"
  database_name             = replace(var.project_name, "-", "_")
  master_username           = "admin"
  master_password           = var.db_password
  node_type                 = var.node_type
  cluster_type              = {'"multi-node"' if num_nodes > 1 else '"single-node"'}
  number_of_nodes           = {num_nodes}
  cluster_subnet_group_name = aws_redshift_subnet_group.main.name
  vpc_security_group_ids    = [aws_security_group.redshift.id]
  skip_final_snapshot       = var.environment != "prod"
  encrypted                 = true
  publicly_accessible       = false

  tags = local.tags
}}

output "cluster_endpoint" {{ value = aws_redshift_cluster.main.endpoint }}
output "cluster_port"     {{ value = aws_redshift_cluster.main.port }}
output "cluster_id"       {{ value = aws_redshift_cluster.main.id }}
"""

        elif warehouse in ("postgresql", "postgres"):
            if provider == "gcp":
                machine_type = self._GCP_MACHINE.get(budget, "n1-standard-4")
                return f"""# modules/warehouse/main.tf — Cloud SQL PostgreSQL (GCP)

variable "project_name" {{ type = string }}
variable "environment"  {{ type = string }}
variable "gcp_project"  {{ type = string }}
variable "region"       {{ type = string }}
variable "db_password"  {{ type = string; sensitive = true }}
variable "machine_type" {{ type = string; default = "{machine_type}" }}

locals {{
  labels = {{
    project     = var.project_name
    environment = var.environment
    managed_by  = "terraform"
  }}
}}

resource "google_sql_database_instance" "main" {{
  name             = "${{var.project_name}}-${{var.environment}}-pg"
  database_version = "POSTGRES_15"
  project          = var.gcp_project
  region           = var.region

  settings {{
    tier = var.machine_type

    backup_configuration {{
      enabled    = true
      start_time = "02:00"
    }}

    ip_configuration {{
      ipv4_enabled    = false
      private_network = "projects/${{var.gcp_project}}/global/networks/default"
    }}
  }}

  deletion_protection = var.environment == "prod"
}}

resource "google_sql_database" "main" {{
  name     = replace(var.project_name, "-", "_")
  instance = google_sql_database_instance.main.name
  project  = var.gcp_project
}}

resource "google_sql_user" "main" {{
  name     = "datasphere"
  instance = google_sql_database_instance.main.name
  password = var.db_password
  project  = var.gcp_project
}}

output "endpoint" {{ value = google_sql_database_instance.main.private_ip_address }}
output "port"     {{ value = 5432 }}
output "db_name"  {{ value = google_sql_database.main.name }}
"""
            else:
                instance_class = self._AWS_DB_INSTANCE.get(budget, "db.r5.large")
                return f"""# modules/warehouse/main.tf — RDS PostgreSQL (AWS)

variable "project_name"    {{ type = string }}
variable "environment"     {{ type = string }}
variable "vpc_id"          {{ type = string }}
variable "subnet_ids"      {{ type = list(string) }}
variable "db_password"     {{ type = string; sensitive = true }}
variable "instance_class"  {{ type = string; default = "{instance_class}" }}

locals {{
  name_prefix = "${{var.project_name}}-${{var.environment}}"
  tags = {{
    Project     = var.project_name
    Environment = var.environment
    ManagedBy   = "terraform"
  }}
}}

resource "aws_db_subnet_group" "main" {{
  name       = "${{local.name_prefix}}-db-subnet"
  subnet_ids = var.subnet_ids
  tags       = local.tags
}}

resource "aws_security_group" "rds" {{
  name        = "${{local.name_prefix}}-rds-sg"
  description = "RDS security group"
  vpc_id      = var.vpc_id

  ingress {{
    from_port   = 5432
    to_port     = 5432
    protocol    = "tcp"
    cidr_blocks = ["10.0.0.0/8"]
    description = "PostgreSQL from internal network"
  }}

  egress {{
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }}

  tags = local.tags
}}

resource "aws_db_instance" "main" {{
  identifier              = "${{local.name_prefix}}-pg"
  engine                  = "postgres"
  engine_version          = "15.4"
  instance_class          = var.instance_class
  allocated_storage       = 100
  max_allocated_storage   = 1000
  storage_type            = "gp3"
  storage_encrypted       = true
  db_name                 = replace(var.project_name, "-", "_")
  username                = "datasphere"
  password                = var.db_password
  db_subnet_group_name    = aws_db_subnet_group.main.name
  vpc_security_group_ids  = [aws_security_group.rds.id]
  multi_az                = var.environment == "prod"
  skip_final_snapshot     = var.environment != "prod"
  deletion_protection     = var.environment == "prod"
  backup_retention_period = 7

  tags = local.tags
}}

output "endpoint"  {{ value = aws_db_instance.main.address }}
output "port"      {{ value = aws_db_instance.main.port }}
output "db_name"   {{ value = aws_db_instance.main.db_name }}
"""

        elif warehouse == "databricks":
            if provider == "azure":
                return """# modules/warehouse/main.tf — Azure Databricks workspace

variable "project_name"   { type = string }
variable "environment"    { type = string }
variable "resource_group" { type = string }
variable "location"       { type = string }

locals {
  tags = {
    Project     = var.project_name
    Environment = var.environment
    ManagedBy   = "terraform"
  }
}

resource "azurerm_databricks_workspace" "main" {
  name                = "${var.project_name}-${var.environment}-databricks"
  resource_group_name = var.resource_group
  location            = var.location
  sku                 = "premium"
  tags                = local.tags
}

output "workspace_id"  { value = azurerm_databricks_workspace.main.id }
output "workspace_url" { value = "https://${azurerm_databricks_workspace.main.workspace_url}" }
"""
            else:
                return """# modules/warehouse/main.tf — Databricks on AWS (E2)

variable "project_name" { type = string }
variable "environment"  { type = string }
variable "vpc_id"       { type = string }
variable "subnet_ids"   { type = list(string) }

locals {
  tags = {
    Project     = var.project_name
    Environment = var.environment
    ManagedBy   = "terraform"
  }
}

resource "databricks_mws_networks" "main" {
  account_id         = var.databricks_account_id
  network_name       = "${var.project_name}-${var.environment}-network"
  security_group_ids = []
  subnet_ids         = var.subnet_ids
  vpc_id             = var.vpc_id
}

resource "databricks_mws_workspaces" "main" {
  account_id     = var.databricks_account_id
  workspace_name = "${var.project_name}-${var.environment}"
  aws_region     = "eu-west-1"
  network_id     = databricks_mws_networks.main.network_id

  token {
    comment = "Terraform-managed token"
  }
}

output "workspace_url" { value = databricks_mws_workspaces.main.workspace_url }
output "workspace_id"  { value = databricks_mws_workspaces.main.workspace_id }
"""

        elif warehouse in ("azure-synapse", "synapse"):
            return """# modules/warehouse/main.tf — Azure Synapse Analytics

variable "project_name"      { type = string }
variable "environment"       { type = string }
variable "resource_group"    { type = string }
variable "location"          { type = string }
variable "synapse_password"  { type = string; sensitive = true }

locals {
  name_prefix = "${var.project_name}-${var.environment}"
  tags = {
    Project     = var.project_name
    Environment = var.environment
    ManagedBy   = "terraform"
  }
}

resource "azurerm_storage_account" "synapse" {
  name                     = "${replace(local.name_prefix, "-", "")}synapse"
  resource_group_name      = var.resource_group
  location                 = var.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
  account_kind             = "StorageV2"
  is_hns_enabled           = true
  tags                     = local.tags
}

resource "azurerm_storage_data_lake_gen2_filesystem" "synapse" {
  name               = "synapse"
  storage_account_id = azurerm_storage_account.synapse.id
}

resource "azurerm_synapse_workspace" "main" {
  name                                 = "${local.name_prefix}-synapse"
  resource_group_name                  = var.resource_group
  location                             = var.location
  storage_data_lake_gen2_filesystem_id = azurerm_storage_data_lake_gen2_filesystem.synapse.id
  sql_administrator_login              = "synapse_admin"
  sql_administrator_login_password     = var.synapse_password
  tags                                 = local.tags
}

resource "azurerm_synapse_sql_pool" "main" {
  name                 = "datawarehouse"
  synapse_workspace_id = azurerm_synapse_workspace.main.id
  sku_name             = "DW100c"
  create_mode          = "Default"
  tags                 = local.tags
}

output "workspace_name" { value = azurerm_synapse_workspace.main.name }
output "sql_endpoint"   { value = azurerm_synapse_workspace.main.connectivity_endpoints["sqlOnDemand"] }
output "workspace_id"   { value = azurerm_synapse_workspace.main.id }
"""

        elif warehouse == "clickhouse":
            return """# modules/warehouse/main.tf — ClickHouse via Helm on Kubernetes

variable "project_name" { type = string }
variable "environment"  { type = string }
variable "namespace"    { type = string; default = "default" }

resource "helm_release" "clickhouse" {
  name             = "${var.project_name}-clickhouse"
  repository       = "https://charts.bitnami.com/bitnami"
  chart            = "clickhouse"
  namespace        = var.namespace
  create_namespace = true
  version          = "4.1.3"

  set {
    name  = "auth.username"
    value = "datasphere"
  }

  set_sensitive {
    name  = "auth.password"
    value = var.clickhouse_password
  }

  set {
    name  = "replicaCount"
    value = "2"
  }
}

variable "clickhouse_password" {
  type      = string
  sensitive = true
  default   = "change-me"
}

output "service_name" { value = helm_release.clickhouse.name }
output "namespace"    { value = helm_release.clickhouse.namespace }
"""

        else:
            # Generic fallback
            return f"""# modules/warehouse/main.tf — {warehouse} (generic)

variable "project_name" {{ type = string }}
variable "environment"  {{ type = string }}

# TODO: Add {warehouse}-specific resources here.
# Refer to the provider documentation for the appropriate resource types.

output "warehouse_name" {{ value = "${{var.project_name}}-${{var.environment}}-{warehouse}" }}
"""

    def _storage_module(self, provider: str, data_lake: str) -> str:
        if provider == "aws" or data_lake in ("s3",):
            return """# modules/storage/main.tf — S3 Data Lake bucket

variable "project_name" { type = string }
variable "environment"  { type = string }
variable "region"       { type = string }

locals {
  bucket_name = "${var.project_name}-${var.environment}-datalake"
  tags = {
    Project     = var.project_name
    Environment = var.environment
    ManagedBy   = "terraform"
  }
}

resource "aws_s3_bucket" "datalake" {
  bucket        = local.bucket_name
  force_destroy = var.environment != "prod"
  tags          = local.tags
}

resource "aws_s3_bucket_versioning" "datalake" {
  bucket = aws_s3_bucket.datalake.id
  versioning_configuration {
    status = "Enabled"
  }
}

resource "aws_s3_bucket_server_side_encryption_configuration" "datalake" {
  bucket = aws_s3_bucket.datalake.id
  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "AES256"
    }
  }
}

resource "aws_s3_bucket_public_access_block" "datalake" {
  bucket                  = aws_s3_bucket.datalake.id
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

resource "aws_s3_object" "prefixes" {
  for_each = toset(["raw/", "staging/", "processed/", "archive/"])
  bucket   = aws_s3_bucket.datalake.id
  key      = each.value
  content  = ""
}

output "bucket_name" { value = aws_s3_bucket.datalake.id }
output "bucket_arn"  { value = aws_s3_bucket.datalake.arn }
output "bucket_uri"  { value = "s3://${aws_s3_bucket.datalake.id}" }
"""

        elif provider == "gcp" or data_lake in ("gcs",):
            return """# modules/storage/main.tf — GCS Data Lake bucket

variable "project_name" { type = string }
variable "environment"  { type = string }
variable "region"       { type = string }
variable "gcp_project"  { type = string }

locals {
  bucket_name = "${var.project_name}-${var.environment}-datalake"
  labels = {
    project     = var.project_name
    environment = var.environment
    managed_by  = "terraform"
  }
}

resource "google_storage_bucket" "datalake" {
  name          = local.bucket_name
  location      = var.region
  project       = var.gcp_project
  storage_class = "STANDARD"
  force_destroy = var.environment != "prod"
  labels        = local.labels

  versioning {
    enabled = true
  }

  uniform_bucket_level_access = true
}

output "bucket_name" { value = google_storage_bucket.datalake.name }
output "bucket_url"  { value = google_storage_bucket.datalake.url }
output "bucket_uri"  { value = "gs://${google_storage_bucket.datalake.name}" }
"""

        elif provider == "azure" or data_lake in ("adls",):
            return """# modules/storage/main.tf — ADLS Gen2 Data Lake

variable "project_name"  { type = string }
variable "environment"   { type = string }
variable "region"        { type = string }
variable "resource_group" { type = string }

locals {
  sa_name = "${replace(var.project_name, "-", "")}${var.environment}lake"
  tags = {
    Project     = var.project_name
    Environment = var.environment
    ManagedBy   = "terraform"
  }
}

resource "azurerm_storage_account" "datalake" {
  name                     = local.sa_name
  resource_group_name      = var.resource_group
  location                 = var.region
  account_tier             = "Standard"
  account_replication_type = "LRS"
  account_kind             = "StorageV2"
  is_hns_enabled           = true
  min_tls_version          = "TLS1_2"
  tags                     = local.tags
}

resource "azurerm_storage_data_lake_gen2_filesystem" "raw" {
  name               = "raw"
  storage_account_id = azurerm_storage_account.datalake.id
}

resource "azurerm_storage_data_lake_gen2_filesystem" "staging" {
  name               = "staging"
  storage_account_id = azurerm_storage_account.datalake.id
}

resource "azurerm_storage_data_lake_gen2_filesystem" "processed" {
  name               = "processed"
  storage_account_id = azurerm_storage_account.datalake.id
}

output "bucket_name"         { value = azurerm_storage_account.datalake.name }
output "storage_account_id"  { value = azurerm_storage_account.datalake.id }
output "bucket_uri"          { value = "abfss://raw@${azurerm_storage_account.datalake.name}.dfs.core.windows.net" }
"""

        else:
            # MinIO fallback
            return """# modules/storage/main.tf — MinIO via Helm (local/kubernetes)

variable "project_name" { type = string }
variable "environment"  { type = string }
variable "region"       { type = string }

resource "helm_release" "minio" {
  name             = "${var.project_name}-minio"
  repository       = "https://charts.min.io"
  chart            = "minio"
  namespace        = var.environment
  create_namespace = true

  set { name = "rootUser";     value = "datasphere" }
  set_sensitive { name = "rootPassword"; value = "change-me-strong-password" }
  set { name = "replicas";     value = "1" }
  set { name = "persistence.size"; value = "50Gi" }
}

output "bucket_name" { value = "${var.project_name}-${var.environment}-minio" }
output "bucket_uri"  { value = "s3://${var.project_name}-${var.environment}-minio" }
"""

    def _kubernetes_module(self, provider: str, budget: str) -> str:
        if provider == "aws":
            instance_type = {"low": "t3.medium", "medium": "m5.xlarge", "enterprise": "m5.4xlarge"}.get(budget, "m5.xlarge")
            return f"""# modules/kubernetes/main.tf — Amazon EKS cluster

variable "project_name"  {{ type = string }}
variable "environment"   {{ type = string }}
variable "region"        {{ type = string }}
variable "vpc_id"        {{ type = string }}
variable "subnet_ids"    {{ type = list(string) }}
variable "instance_type" {{ type = string; default = "{instance_type}" }}

locals {{
  cluster_name = "${{var.project_name}}-${{var.environment}}-eks"
  tags = {{
    Project     = var.project_name
    Environment = var.environment
    ManagedBy   = "terraform"
  }}
}}

data "aws_iam_policy_document" "eks_assume_role" {{
  statement {{
    effect = "Allow"
    principals {{
      type        = "Service"
      identifiers = ["eks.amazonaws.com"]
    }}
    actions = ["sts:AssumeRole"]
  }}
}}

resource "aws_iam_role" "eks_cluster" {{
  name               = "${{local.cluster_name}}-role"
  assume_role_policy = data.aws_iam_policy_document.eks_assume_role.json
  tags               = local.tags
}}

resource "aws_iam_role_policy_attachment" "eks_cluster_policy" {{
  policy_arn = "arn:aws:iam::aws:policy/AmazonEKSClusterPolicy"
  role       = aws_iam_role.eks_cluster.name
}}

resource "aws_eks_cluster" "main" {{
  name     = local.cluster_name
  role_arn = aws_iam_role.eks_cluster.arn
  version  = "1.29"

  vpc_config {{
    subnet_ids              = var.subnet_ids
    endpoint_private_access = true
    endpoint_public_access  = true
  }}

  tags = local.tags

  depends_on = [aws_iam_role_policy_attachment.eks_cluster_policy]
}}

data "aws_iam_policy_document" "node_assume_role" {{
  statement {{
    effect = "Allow"
    principals {{
      type        = "Service"
      identifiers = ["ec2.amazonaws.com"]
    }}
    actions = ["sts:AssumeRole"]
  }}
}}

resource "aws_iam_role" "node_group" {{
  name               = "${{local.cluster_name}}-node-role"
  assume_role_policy = data.aws_iam_policy_document.node_assume_role.json
  tags               = local.tags
}}

resource "aws_iam_role_policy_attachment" "node_worker_policy" {{
  policy_arn = "arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy"
  role       = aws_iam_role.node_group.name
}}

resource "aws_iam_role_policy_attachment" "node_cni_policy" {{
  policy_arn = "arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy"
  role       = aws_iam_role.node_group.name
}}

resource "aws_iam_role_policy_attachment" "node_registry_policy" {{
  policy_arn = "arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly"
  role       = aws_iam_role.node_group.name
}}

resource "aws_eks_node_group" "main" {{
  cluster_name    = aws_eks_cluster.main.name
  node_group_name = "${{local.cluster_name}}-workers"
  node_role_arn   = aws_iam_role.node_group.arn
  subnet_ids      = var.subnet_ids
  instance_types  = [var.instance_type]

  scaling_config {{
    desired_size = 2
    min_size     = 1
    max_size     = 5
  }}

  update_config {{
    max_unavailable = 1
  }}

  tags = local.tags

  depends_on = [
    aws_iam_role_policy_attachment.node_worker_policy,
    aws_iam_role_policy_attachment.node_cni_policy,
    aws_iam_role_policy_attachment.node_registry_policy,
  ]
}}

output "cluster_name"     {{ value = aws_eks_cluster.main.name }}
output "cluster_endpoint" {{ value = aws_eks_cluster.main.endpoint }}
output "cluster_ca"       {{ value = aws_eks_cluster.main.certificate_authority[0].data }}
"""

        elif provider == "gcp":
            machine_type = self._GCP_MACHINE.get(budget, "n1-standard-4")
            return f"""# modules/kubernetes/main.tf — GKE cluster

variable "project_name"  {{ type = string }}
variable "environment"   {{ type = string }}
variable "region"        {{ type = string }}
variable "network"       {{ type = string }}
variable "subnetwork"    {{ type = string }}
variable "machine_type"  {{ type = string; default = "{machine_type}" }}

locals {{
  cluster_name = "${{var.project_name}}-${{var.environment}}-gke"
  labels = {{
    project     = var.project_name
    environment = var.environment
    managed_by  = "terraform"
  }}
}}

resource "google_container_cluster" "main" {{
  name     = local.cluster_name
  location = var.region

  network    = var.network
  subnetwork = var.subnetwork

  remove_default_node_pool = true
  initial_node_count       = 1

  ip_allocation_policy {{
    cluster_secondary_range_name  = "pods"
    services_secondary_range_name = "services"
  }}

  workload_identity_config {{
    workload_pool = "${{data.google_client_config.default.project}}.svc.id.goog"
  }}

  resource_labels = local.labels
}}

data "google_client_config" "default" {{}}

resource "google_container_node_pool" "main" {{
  name       = "${{local.cluster_name}}-pool"
  cluster    = google_container_cluster.main.name
  location   = var.region
  node_count = 2

  node_config {{
    machine_type = var.machine_type
    disk_size_gb = 100
    disk_type    = "pd-ssd"

    workload_metadata_config {{
      mode = "GKE_METADATA"
    }}

    labels  = local.labels
    oauth_scopes = [
      "https://www.googleapis.com/auth/cloud-platform",
    ]
  }}

  autoscaling {{
    min_node_count = 1
    max_node_count = 5
  }}

  management {{
    auto_repair  = true
    auto_upgrade = true
  }}
}}

output "cluster_name"     {{ value = google_container_cluster.main.name }}
output "cluster_endpoint" {{ value = google_container_cluster.main.endpoint }}
"""

        elif provider == "azure":
            vm_size = self._AZURE_VM.get(budget, "Standard_D4s_v3")
            return f"""# modules/kubernetes/main.tf — AKS cluster

variable "project_name"   {{ type = string }}
variable "environment"    {{ type = string }}
variable "region"         {{ type = string }}
variable "resource_group" {{ type = string }}
variable "vm_size"        {{ type = string; default = "{vm_size}" }}

locals {{
  cluster_name = "${{var.project_name}}-${{var.environment}}-aks"
  tags = {{
    Project     = var.project_name
    Environment = var.environment
    ManagedBy   = "terraform"
  }}
}}

resource "azurerm_kubernetes_cluster" "main" {{
  name                = local.cluster_name
  location            = var.region
  resource_group_name = var.resource_group
  dns_prefix          = "${{var.project_name}}-${{var.environment}}"
  kubernetes_version  = "1.29"

  default_node_pool {{
    name           = "default"
    node_count     = 2
    vm_size        = var.vm_size
    os_disk_size_gb = 100
    type           = "VirtualMachineScaleSets"
  }}

  identity {{
    type = "SystemAssigned"
  }}

  tags = local.tags
}}

output "cluster_name"     {{ value = azurerm_kubernetes_cluster.main.name }}
output "cluster_endpoint" {{ value = azurerm_kubernetes_cluster.main.kube_config[0].host }}
output "kube_config_raw"  {{ value = azurerm_kubernetes_cluster.main.kube_config_raw; sensitive = true }}
"""

        else:
            return """# modules/kubernetes/main.tf — Local Kubernetes (kind/minikube)

variable "project_name" { type = string }
variable "environment"  { type = string }
variable "region"       { type = string }

resource "kubernetes_namespace" "datasphere" {
  metadata {
    name = "${var.project_name}-${var.environment}"
    labels = {
      "app.kubernetes.io/managed-by" = "terraform"
      environment                    = var.environment
    }
  }
}

output "cluster_name"     { value = "local" }
output "cluster_endpoint" { value = "https://localhost:6443" }
output "namespace"        { value = kubernetes_namespace.datasphere.metadata[0].name }
"""

    def _monitoring_module(self) -> str:
        return """# modules/monitoring/main.tf — Prometheus + Grafana via kube-prometheus-stack

variable "project_name" { type = string }
variable "environment"  { type = string }

locals {
  namespace = "${var.project_name}-monitoring"
}

resource "kubernetes_namespace" "monitoring" {
  metadata {
    name = local.namespace
    labels = {
      "app.kubernetes.io/managed-by" = "terraform"
      environment                    = var.environment
    }
  }
}

resource "helm_release" "kube_prometheus_stack" {
  name             = "kube-prometheus-stack"
  repository       = "https://prometheus-community.github.io/helm-charts"
  chart            = "kube-prometheus-stack"
  namespace        = kubernetes_namespace.monitoring.metadata[0].name
  version          = "57.2.0"
  create_namespace = false

  values = [
    yamlencode({
      grafana = {
        adminPassword = "change-me-grafana-password"
        persistence = {
          enabled      = true
          size         = "10Gi"
        }
        dashboardProviders = {
          "dashboardproviders.yaml" = {
            apiVersion = 1
            providers  = [{
              name            = "datasphere"
              orgId           = 1
              folder          = "DataSphere"
              type            = "file"
              disableDeletion = false
              editable        = true
              options         = { path = "/var/lib/grafana/dashboards/datasphere" }
            }]
          }
        }
      }
      prometheus = {
        prometheusSpec = {
          retention           = "30d"
          retentionSize       = "50GB"
          storageSpec = {
            volumeClaimTemplate = {
              spec = {
                resources = { requests = { storage = "50Gi" } }
              }
            }
          }
        }
      }
    })
  ]

  depends_on = [kubernetes_namespace.monitoring]
}

output "grafana_url"      { value = "http://grafana.${local.namespace}.svc.cluster.local" }
output "prometheus_url"   { value = "http://kube-prometheus-stack-prometheus.${local.namespace}.svc.cluster.local:9090" }
output "namespace"        { value = local.namespace }
"""

    def _iam_module(self, provider: str) -> str:
        if provider == "aws":
            return """# modules/iam/main.tf — AWS IAM roles and policies for the platform

variable "project_name" { type = string }
variable "environment"  { type = string }
variable "bucket_name"  { type = string; default = "" }

locals {
  name_prefix = "${var.project_name}-${var.environment}"
  tags = {
    Project     = var.project_name
    Environment = var.environment
    ManagedBy   = "terraform"
  }
}

# ── Data platform service role ──────────────────────────────────────────

data "aws_iam_policy_document" "ec2_assume_role" {
  statement {
    effect = "Allow"
    principals {
      type        = "Service"
      identifiers = ["ec2.amazonaws.com"]
    }
    actions = ["sts:AssumeRole"]
  }
}

resource "aws_iam_role" "platform" {
  name               = "${local.name_prefix}-platform-role"
  assume_role_policy = data.aws_iam_policy_document.ec2_assume_role.json
  tags               = local.tags
}

data "aws_iam_policy_document" "platform_policy" {
  statement {
    effect    = "Allow"
    actions   = ["s3:GetObject", "s3:PutObject", "s3:DeleteObject", "s3:ListBucket"]
    resources = [
      "arn:aws:s3:::${var.bucket_name}",
      "arn:aws:s3:::${var.bucket_name}/*",
    ]
    condition {
      test     = "StringNotEquals"
      variable = "s3:prefix"
      values   = [""]
    }
  }

  statement {
    effect    = "Allow"
    actions   = ["secretsmanager:GetSecretValue"]
    resources = ["arn:aws:secretsmanager:*:*:secret:${local.name_prefix}/*"]
  }

  statement {
    effect    = "Allow"
    actions   = ["logs:CreateLogGroup", "logs:CreateLogStream", "logs:PutLogEvents"]
    resources = ["arn:aws:logs:*:*:log-group:/datasphere/${local.name_prefix}:*"]
  }
}

resource "aws_iam_policy" "platform" {
  name   = "${local.name_prefix}-platform-policy"
  policy = data.aws_iam_policy_document.platform_policy.json
  tags   = local.tags
}

resource "aws_iam_role_policy_attachment" "platform" {
  role       = aws_iam_role.platform.name
  policy_arn = aws_iam_policy.platform.arn
}

# ── CI/CD deploy role ───────────────────────────────────────────────────

data "aws_iam_policy_document" "cicd_deploy" {
  statement {
    effect    = "Allow"
    actions   = ["s3:*"]
    resources = [
      "arn:aws:s3:::${var.bucket_name}",
      "arn:aws:s3:::${var.bucket_name}/*",
    ]
  }
  statement {
    effect    = "Allow"
    actions   = ["ecr:GetAuthorizationToken", "ecr:BatchCheckLayerAvailability",
                 "ecr:GetDownloadUrlForLayer", "ecr:BatchGetImage",
                 "ecr:PutImage", "ecr:InitiateLayerUpload",
                 "ecr:UploadLayerPart", "ecr:CompleteLayerUpload"]
    resources = ["*"]
  }
}

resource "aws_iam_policy" "cicd_deploy" {
  name   = "${local.name_prefix}-cicd-deploy-policy"
  policy = data.aws_iam_policy_document.cicd_deploy.json
  tags   = local.tags
}

output "platform_role_arn"    { value = aws_iam_role.platform.arn }
output "platform_role_name"   { value = aws_iam_role.platform.name }
output "cicd_policy_arn"      { value = aws_iam_policy.cicd_deploy.arn }
"""

        elif provider == "gcp":
            return """# modules/iam/main.tf — GCP IAM service accounts and bindings

variable "project_name" { type = string }
variable "environment"  { type = string }
variable "gcp_project"  { type = string }

locals {
  name_prefix = "${var.project_name}-${var.environment}"
  labels = {
    project     = var.project_name
    environment = var.environment
    managed_by  = "terraform"
  }
}

# ── Platform service account ────────────────────────────────────────────

resource "google_service_account" "platform" {
  account_id   = "${local.name_prefix}-sa"
  display_name = "DataSphere Platform Service Account"
  project      = var.gcp_project
}

resource "google_project_iam_member" "platform_bigquery_user" {
  project = var.gcp_project
  role    = "roles/bigquery.user"
  member  = "serviceAccount:${google_service_account.platform.email}"
}

resource "google_project_iam_member" "platform_bigquery_dataeditor" {
  project = var.gcp_project
  role    = "roles/bigquery.dataEditor"
  member  = "serviceAccount:${google_service_account.platform.email}"
}

resource "google_project_iam_member" "platform_storage_objectadmin" {
  project = var.gcp_project
  role    = "roles/storage.objectAdmin"
  member  = "serviceAccount:${google_service_account.platform.email}"
}

resource "google_project_iam_member" "platform_secretaccessor" {
  project = var.gcp_project
  role    = "roles/secretmanager.secretAccessor"
  member  = "serviceAccount:${google_service_account.platform.email}"
}

# ── Workload Identity for GKE ───────────────────────────────────────────

resource "google_service_account_iam_member" "workload_identity" {
  service_account_id = google_service_account.platform.name
  role               = "roles/iam.workloadIdentityUser"
  member             = "serviceAccount:${var.gcp_project}.svc.id.goog[${var.environment}/datasphere-sa]"
}

output "platform_sa_email"  { value = google_service_account.platform.email }
output "platform_sa_id"     { value = google_service_account.platform.id }
"""

        elif provider == "azure":
            return """# modules/iam/main.tf — Azure IAM (Managed Identity + Role Assignments)

variable "project_name"   { type = string }
variable "environment"    { type = string }
variable "resource_group" { type = string }

locals {
  name_prefix = "${var.project_name}-${var.environment}"
  tags = {
    Project     = var.project_name
    Environment = var.environment
    ManagedBy   = "terraform"
  }
}

data "azurerm_resource_group" "main" {
  name = var.resource_group
}

resource "azurerm_user_assigned_identity" "platform" {
  name                = "${local.name_prefix}-identity"
  resource_group_name = var.resource_group
  location            = data.azurerm_resource_group.main.location
  tags                = local.tags
}

resource "azurerm_role_assignment" "storage_contributor" {
  scope                = data.azurerm_resource_group.main.id
  role_definition_name = "Storage Blob Data Contributor"
  principal_id         = azurerm_user_assigned_identity.platform.principal_id
}

resource "azurerm_role_assignment" "key_vault_reader" {
  scope                = data.azurerm_resource_group.main.id
  role_definition_name = "Key Vault Secrets User"
  principal_id         = azurerm_user_assigned_identity.platform.principal_id
}

output "identity_id"       { value = azurerm_user_assigned_identity.platform.id }
output "identity_client_id" { value = azurerm_user_assigned_identity.platform.client_id }
output "principal_id"      { value = azurerm_user_assigned_identity.platform.principal_id }
"""

        else:
            return """# modules/iam/main.tf — Minimal IAM (local/kubernetes)

variable "project_name" { type = string }
variable "environment"  { type = string }

# For local-docker / kubernetes deployments, IAM is handled by
# Kubernetes RBAC and service accounts.

resource "kubernetes_service_account" "platform" {
  metadata {
    name      = "${var.project_name}-sa"
    namespace = var.environment
    labels = {
      "app.kubernetes.io/managed-by" = "terraform"
    }
  }
}

resource "kubernetes_cluster_role_binding" "platform" {
  metadata {
    name = "${var.project_name}-${var.environment}-binding"
  }

  role_ref {
    api_group = "rbac.authorization.k8s.io"
    kind      = "ClusterRole"
    name      = "view"
  }

  subject {
    kind      = "ServiceAccount"
    name      = kubernetes_service_account.platform.metadata[0].name
    namespace = var.environment
  }
}

output "service_account_name" { value = kubernetes_service_account.platform.metadata[0].name }
"""
