from __future__ import annotations
from datasphere.agents.base_agent import BaseAgent
from datasphere.models.request import BusinessRequest, ArchitectureConstraints
from datasphere.models.output import AgentOutput, InfrastructureOutput


class InfrastructureAgent(BaseAgent):
    name = "infrastructure"
    description = "Génère Docker Compose, Helm values ou Terraform selon la stack choisie."

    def _run(self, request: BusinessRequest, context: dict) -> InfrastructureOutput:
        c = self._constraints(request)
        depl = c.deployment.lower().replace(" ", "-")

        artifacts: dict[str, str] = {}

        if "kubernetes" in depl or "helm" in depl:
            artifacts["helm/values.yaml"] = self._helm_values(c)
            artifacts["helm/values.override.yaml"] = self._helm_override(c)
            artifacts["k8s/namespace.yaml"] = self._k8s_namespace()
            artifacts["k8s/secrets.yaml"] = self._k8s_secrets(c)
            deployment_type = "kubernetes/helm"
        elif "terraform" in depl or (c.iac and "terraform" in c.iac.lower()):
            artifacts["terraform/main.tf"] = self._terraform_main(c)
            artifacts["terraform/variables.tf"] = self._terraform_vars(c)
            artifacts["terraform/outputs.tf"] = self._terraform_outputs(c)
            artifacts["terraform/terraform.tfvars.example"] = self._tfvars_example(c)
            deployment_type = "terraform"
        else:
            artifacts["docker-compose.yml"] = self._docker_compose(c)
            artifacts[".env.example"] = self._env_example(c)
            artifacts["Makefile"] = self._makefile(c)
            deployment_type = "docker-compose"

        output = InfrastructureOutput(deployment_type=deployment_type)
        output.artifacts = artifacts
        return output

    # ------------------------------------------------------------------
    # Docker Compose
    # ------------------------------------------------------------------

    def _docker_compose(self, c: ArchitectureConstraints) -> str:
        services: list[str] = []
        volumes: list[str] = []

        services.append(self._svc_warehouse(c))
        volumes.append(f"  {c.data_warehouse}_data:")

        services.append(self._svc_orchestrator(c))
        if c.orchestrator == "airflow":
            volumes.append("  airflow_logs:")

        if c.data_lake and c.data_lake not in ("none", "s3", "adls", "gcs"):
            services.append(self._svc_minio())
            volumes.append("  minio_data:")

        services.append(self._svc_bi(c))
        volumes.append(f"  {c.bi_tool}_data:")

        if c.catalog:
            services.append(self._svc_catalog(c))

        services.append(self._svc_monitoring(c))
        volumes += ["  prometheus_data:", "  grafana_data:"]

        if "vault" in [s.lower() for s in c.security]:
            services.append(self._svc_vault())
            volumes.append("  vault_data:")

        return "\n".join([
            "version: '3.9'",
            "",
            "# Auto-generated by DataSphere Infrastructure Agent",
            f"# Stack: {c.cloud_provider} | {c.data_warehouse} | {c.orchestrator} | {c.bi_tool}",
            "",
            "services:",
            *services,
            "",
            "volumes:",
            *volumes,
            "",
            "networks:",
            "  datasphere:",
            "    driver: bridge",
        ])

    def _svc_warehouse(self, c: ArchitectureConstraints) -> str:
        wh = c.data_warehouse
        if wh == "postgresql":
            return """  postgresql:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-datasphere}
      POSTGRES_USER: ${POSTGRES_USER:-datasphere}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?required}
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-datasphere}"]
      interval: 10s
      retries: 5
    networks: [datasphere]
    restart: unless-stopped"""

        if wh == "clickhouse":
            return """  clickhouse:
    image: clickhouse/clickhouse-server:23.8
    environment:
      CLICKHOUSE_DB: datasphere
      CLICKHOUSE_USER: ${CLICKHOUSE_USER:-datasphere}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD:?required}
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    ulimits:
      nofile: {soft: 262144, hard: 262144}
    networks: [datasphere]
    restart: unless-stopped"""

        # Snowflake / BigQuery / Redshift etc. are SaaS — no local container
        return f"""  # {wh} est un service SaaS — pas de container local
  # Configurez les credentials dans .env"""

    def _svc_orchestrator(self, c: ArchitectureConstraints) -> str:
        if c.orchestrator == "airflow":
            return """  airflow-webserver:
    image: apache/airflow:2.8.0
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgresql/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW_SECRET_KEY:?required}
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - airflow_logs:/opt/airflow/logs
    command: webserver
    depends_on: [postgresql]
    networks: [datasphere]
    restart: unless-stopped

  airflow-scheduler:
    image: apache/airflow:2.8.0
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgresql/airflow
    volumes:
      - ./dags:/opt/airflow/dags
      - airflow_logs:/opt/airflow/logs
    command: scheduler
    depends_on: [postgresql]
    networks: [datasphere]
    restart: unless-stopped"""

        if c.orchestrator == "dagster":
            return """  dagster:
    image: ghcr.io/dagster-io/dagster:latest
    ports:
      - "3000:3000"
    environment:
      DAGSTER_HOME: /opt/dagster/dagster_home
      DAGSTER_PG_USERNAME: ${POSTGRES_USER}
      DAGSTER_PG_PASSWORD: ${POSTGRES_PASSWORD}
      DAGSTER_PG_DB: dagster
    volumes:
      - ./pipeline:/opt/dagster/app
    depends_on: [postgresql]
    networks: [datasphere]
    restart: unless-stopped"""

        if c.orchestrator == "prefect":
            return """  prefect:
    image: prefecthq/prefect:2-latest
    command: prefect server start --host 0.0.0.0
    ports:
      - "4200:4200"
    environment:
      PREFECT_API_DATABASE_CONNECTION_URL: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgresql/prefect
    depends_on: [postgresql]
    networks: [datasphere]
    restart: unless-stopped"""

        return f"  # {c.orchestrator} — configurez manuellement"

    def _svc_minio(self) -> str:
        return """  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:?required}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      retries: 3
    networks: [datasphere]
    restart: unless-stopped"""

    def _svc_bi(self, c: ArchitectureConstraints) -> str:
        bi = c.bi_tool
        if bi == "superset":
            return """  superset:
    image: apache/superset:latest
    ports:
      - "8088:8088"
    environment:
      SUPERSET_SECRET_KEY: ${SUPERSET_SECRET_KEY:?required}
      DATABASE_URL: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgresql/superset
    depends_on: [postgresql]
    networks: [datasphere]
    restart: unless-stopped"""

        if bi == "metabase":
            return """  metabase:
    image: metabase/metabase:latest
    ports:
      - "3001:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_HOST: postgresql
      MB_DB_PORT: 5432
      MB_DB_DBNAME: metabase
      MB_DB_USER: ${POSTGRES_USER}
      MB_DB_PASS: ${POSTGRES_PASSWORD}
    depends_on: [postgresql]
    volumes:
      - metabase_data:/metabase-data
    networks: [datasphere]
    restart: unless-stopped"""

        return f"  # {bi} — configurez manuellement"

    def _svc_catalog(self, c: ArchitectureConstraints) -> str:
        if c.catalog in ("openmetadata", "OpenMetadata"):
            return """  openmetadata:
    image: openmetadata/server:latest
    ports:
      - "8585:8585"
    environment:
      DB_HOST: postgresql
      DB_PORT: 5432
      DB_USER: ${POSTGRES_USER}
      DB_USER_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on: [postgresql]
    networks: [datasphere]"""
        return f"  # {c.catalog} — configurez manuellement"

    def _svc_monitoring(self, c: ArchitectureConstraints) -> str:
        return """  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command: ['--config.file=/etc/prometheus/prometheus.yml', '--web.enable-lifecycle']
    networks: [datasphere]
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3002:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD:?required}
    volumes:
      - grafana_data:/var/lib/grafana
    networks: [datasphere]
    restart: unless-stopped"""

    def _svc_vault(self) -> str:
        return """  vault:
    image: hashicorp/vault:latest
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: ${VAULT_TOKEN:?required}
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    cap_add: [IPC_LOCK]
    volumes:
      - vault_data:/vault/data
    networks: [datasphere]
    restart: unless-stopped"""

    def _env_example(self, c: ArchitectureConstraints) -> str:
        lines = [
            "# DataSphere — Variables d'environnement",
            "# Copiez ce fichier en .env et remplissez les valeurs",
            "",
            "# Database",
            "POSTGRES_DB=datasphere",
            "POSTGRES_USER=datasphere",
            "POSTGRES_PASSWORD=changeme_strong_password",
            "",
        ]
        if c.orchestrator == "airflow":
            lines += ["# Airflow", "AIRFLOW_SECRET_KEY=changeme_32chars_minimum", ""]
        if c.data_lake and c.data_lake not in ("none", "s3", "adls", "gcs"):
            lines += ["# MinIO", "MINIO_ROOT_USER=minioadmin", "MINIO_ROOT_PASSWORD=changeme", ""]
        if c.bi_tool == "superset":
            lines += ["# Superset", "SUPERSET_SECRET_KEY=changeme_32chars_minimum", ""]
        if "vault" in [s.lower() for s in c.security]:
            lines += ["# Vault", "VAULT_TOKEN=root-dev-token", ""]
        if c.data_warehouse == "snowflake":
            lines += ["# Snowflake", "SNOWFLAKE_ACCOUNT=", "SNOWFLAKE_USER=", "SNOWFLAKE_PASSWORD=", "SNOWFLAKE_WAREHOUSE=", "SNOWFLAKE_DATABASE=datasphere", ""]
        if c.data_warehouse == "bigquery":
            lines += ["# BigQuery", "GOOGLE_APPLICATION_CREDENTIALS=/secrets/sa.json", "GCP_PROJECT=", ""]
        lines += ["# Monitoring", "GRAFANA_PASSWORD=changeme"]
        return "\n".join(lines)

    def _makefile(self, c: ArchitectureConstraints) -> str:
        orch = c.orchestrator
        return f"""# DataSphere Makefile
.PHONY: up down logs status init-airflow

up:
\tdocker compose up -d

down:
\tdocker compose down

logs:
\tdocker compose logs -f

status:
\tdocker compose ps

init-airflow:
\tdocker compose run --rm airflow-webserver airflow db init
\tdocker compose run --rm airflow-webserver airflow users create \\
\t\t--username admin --password admin \\
\t\t--firstname Admin --lastname User \\
\t\t--role Admin --email admin@example.com

dbt-run:
\tdocker compose run --rm dbt dbt run

dbt-test:
\tdocker compose run --rm dbt dbt test

validate:
\tdatasphere validate stack.yaml
"""

    # ------------------------------------------------------------------
    # Helm values
    # ------------------------------------------------------------------

    def _helm_values(self, c: ArchitectureConstraints) -> str:
        wh = c.data_warehouse
        return f"""# DataSphere Helm Values
# Auto-generated by DataSphere Infrastructure Agent

global:
  imageRegistry: ""
  storageClass: ""

platform:
  name: datasphere
  environment: production

# Warehouse
{wh}:
  enabled: {str(wh in ('postgresql', 'clickhouse')).lower()}
  auth:
    existingSecret: datasphere-{wh}-secret

# Orchestration
{c.orchestrator}:
  enabled: true
  executor: KubernetesExecutor
  dags:
    persistence:
      enabled: true
      size: 5Gi

# BI
{c.bi_tool}:
  enabled: true
  existingSecret: datasphere-{c.bi_tool}-secret

# Storage
minio:
  enabled: {str(c.data_lake not in ('s3', 'adls', 'gcs', 'none', None)).lower()}
  persistence:
    size: 50Gi

# Security
vault:
  enabled: {str('vault' in [s.lower() for s in c.security]).lower()}

keycloak:
  enabled: {str('keycloak' in [s.lower() for s in c.security]).lower()}

# Monitoring
prometheus:
  enabled: true
  server:
    persistentVolume:
      size: 20Gi

grafana:
  enabled: true
  persistence:
    enabled: true

# Ingress
ingress:
  enabled: false
  className: nginx
  host: datasphere.example.com
"""

    def _helm_override(self, c: ArchitectureConstraints) -> str:
        cloud = c.cloud_provider
        storage_classes = {
            "aws": "gp3", "azure": "managed-premium",
            "gcp": "standard-rwo", "kubernetes": "local-path",
        }
        return f"""# Cloud-specific overrides — {cloud}
global:
  storageClass: {storage_classes.get(cloud, 'standard')}

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: {"alb" if cloud == "aws" else "nginx"}
"""

    def _k8s_namespace(self) -> str:
        return """apiVersion: v1
kind: Namespace
metadata:
  name: datasphere
  labels:
    name: datasphere
    managed-by: datasphere-agent
---
apiVersion: v1
kind: Namespace
metadata:
  name: datasphere-monitoring
  labels:
    name: datasphere-monitoring
"""

    def _k8s_secrets(self, c: ArchitectureConstraints) -> str:
        return f"""# DataSphere Kubernetes Secrets Template
# Use External Secrets Operator or Vault Agent Injector in production
# Never commit real values to git

apiVersion: v1
kind: Secret
metadata:
  name: datasphere-{c.data_warehouse}-secret
  namespace: datasphere
type: Opaque
stringData:
  password: REPLACE_ME  # inject via Vault or External Secrets
  username: datasphere

---
apiVersion: v1
kind: Secret
metadata:
  name: datasphere-{c.bi_tool}-secret
  namespace: datasphere
type: Opaque
stringData:
  secret-key: REPLACE_ME
"""

    # ------------------------------------------------------------------
    # Terraform
    # ------------------------------------------------------------------

    def _terraform_main(self, c: ArchitectureConstraints) -> str:
        cloud = c.cloud_provider
        if cloud == "aws":
            return self._tf_aws(c)
        if cloud == "azure":
            return self._tf_azure(c)
        if cloud == "gcp":
            return self._tf_gcp(c)
        return f'# Terraform pour {cloud} — à compléter\n'

    def _tf_aws(self, c: ArchitectureConstraints) -> str:
        eks_block = (
            'module "eks" {\n'
            '  source  = "terraform-aws-modules/eks/aws"\n'
            '  version = "~> 20.0"\n'
            '  cluster_name = "datasphere-${var.environment}"\n'
            '  vpc_id       = module.vpc.vpc_id\n'
            '  subnet_ids   = module.vpc.private_subnets\n'
            '}'
        ) if "kubernetes" in c.deployment.lower() else ""
        return f"""terraform {{
  required_version = ">= 1.5"
  required_providers {{
    aws = {{ source = "hashicorp/aws", version = "~> 5.0" }}
  }}
  backend "s3" {{
    bucket = var.tf_state_bucket
    key    = "datasphere/{c.data_warehouse}/terraform.tfstate"
    region = var.region
  }}
}}

provider "aws" {{
  region = var.region
  default_tags {{
    tags = {{
      Project     = "datasphere"
      Environment = var.environment
      ManagedBy   = "terraform"
    }}
  }}
}}

module "vpc" {{
  source  = "terraform-aws-modules/vpc/aws"
  version = "~> 5.0"
  name    = "datasphere-${{var.environment}}"
  cidr    = "10.0.0.0/16"
  azs             = ["${{var.region}}a", "${{var.region}}b", "${{var.region}}c"]
  private_subnets = ["10.0.1.0/24", "10.0.2.0/24", "10.0.3.0/24"]
  public_subnets  = ["10.0.101.0/24", "10.0.102.0/24", "10.0.103.0/24"]
  enable_nat_gateway = true
  single_nat_gateway = var.environment != "production"
}}

{eks_block}

resource "aws_s3_bucket" "data_lake" {{
  bucket = "datasphere-${{var.environment}}-${{data.aws_caller_identity.current.account_id}}"
}}
resource "aws_s3_bucket_versioning" "data_lake" {{
  bucket = aws_s3_bucket.data_lake.id
  versioning_configuration {{ status = "Enabled" }}
}}

data "aws_caller_identity" "current" {{}}
"""

    def _tf_azure(self, c: ArchitectureConstraints) -> str:
        return f"""terraform {{
  required_version = ">= 1.5"
  required_providers {{
    azurerm = {{ source = "hashicorp/azurerm", version = "~> 3.0" }}
  }}
}}

provider "azurerm" {{
  features {{}}
  subscription_id = var.subscription_id
}}

resource "azurerm_resource_group" "main" {{
  name     = "datasphere-${{var.environment}}"
  location = var.location
  tags = {{ environment = var.environment, project = "datasphere" }}
}}

resource "azurerm_storage_account" "data_lake" {{
  name                     = "datasphere${{var.environment}}"
  resource_group_name      = azurerm_resource_group.main.name
  location                 = azurerm_resource_group.main.location
  account_tier             = "Standard"
  account_replication_type = var.environment == "production" ? "GRS" : "LRS"
  account_kind             = "StorageV2"
  is_hns_enabled           = true
}}
"""

    def _tf_gcp(self, c: ArchitectureConstraints) -> str:
        return f"""terraform {{
  required_version = ">= 1.5"
  required_providers {{
    google = {{ source = "hashicorp/google", version = "~> 5.0" }}
  }}
}}

provider "google" {{
  project = var.project
  region  = var.region
}}

resource "google_storage_bucket" "data_lake" {{
  name          = "${{var.project}}-datasphere-${{var.environment}}"
  location      = upper(var.region)
  force_destroy = var.environment != "production"
  versioning {{ enabled = true }}
}}

resource "google_bigquery_dataset" "main" {{
  dataset_id = "datasphere"
  location   = upper(var.region)
}}
"""

    def _terraform_vars(self, c: ArchitectureConstraints) -> str:
        cloud = c.cloud_provider
        base = 'variable "environment" { default = "production" }\n'
        if cloud == "aws":
            return base + 'variable "region" { default = "eu-west-1" }\nvariable "tf_state_bucket" {}\n'
        if cloud == "azure":
            return base + 'variable "subscription_id" {}\nvariable "location" { default = "West Europe" }\n'
        if cloud == "gcp":
            return base + 'variable "project" {}\nvariable "region" { default = "europe-west1" }\n'
        return base

    def _terraform_outputs(self, c: ArchitectureConstraints) -> str:
        cloud = c.cloud_provider
        if cloud == "aws":
            return 'output "data_lake_bucket" { value = aws_s3_bucket.data_lake.bucket }\n'
        if cloud == "azure":
            return 'output "adls_account" { value = azurerm_storage_account.data_lake.name }\n'
        if cloud == "gcp":
            return 'output "gcs_bucket" { value = google_storage_bucket.data_lake.name }\n'
        return ""

    def _tfvars_example(self, c: ArchitectureConstraints) -> str:
        cloud = c.cloud_provider
        lines = ['environment = "production"']
        if cloud == "aws":
            lines += ['region = "eu-west-1"', 'tf_state_bucket = "my-terraform-state-bucket"']
        if cloud == "azure":
            lines += ['subscription_id = "00000000-0000-0000-0000-000000000000"', 'location = "West Europe"']
        if cloud == "gcp":
            lines += ['project = "my-gcp-project"', 'region = "europe-west1"']
        return "\n".join(lines) + "\n"
