apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "datasphere.fullname" . }}-config
  labels:
    {{- include "datasphere.labels" . | nindent 4 }}
data:
  PLATFORM_NAME: {{ .Values.platform.name | quote }}
  PLATFORM_ENV: {{ .Values.platform.environment | quote }}
