apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "datasphere.fullname" . }}
  labels:
    {{- include "datasphere.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.platform.replicaCount }}
  selector:
    matchLabels:
      {{- include "datasphere.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "datasphere.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.global.imageRegistry }}/datasphere/api:{{ .Chart.AppVersion }}"
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "datasphere.fullname" . }}-config
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
