{{- if .Values.api.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "datasphere.fullname" . }}-api-secret
  labels:
    {{- include "datasphere.labels" . | nindent 4 }}
type: Opaque
data:
  api-key: {{ .Values.api.apiKey | b64enc | quote }}
{{- end }}
